"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { createClient } from "@/lib/supabase/client";
type Post={id:string;author_id:string;body:string;post_reactions:{user_id:string}[]};
export function CommunityPage({userId}:{userId:string}){
 const [posts,setPosts]=useState<Post[]>([]);const [body,setBody]=useState("");const [message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{const r=await createClient().from("posts").select("id,author_id,body,post_reactions(user_id)").eq("status","published").order("created_at",{ascending:false}).limit(50);if(r.error)setMessage("โหลดโพสต์ไม่สำเร็จ");else setPosts((r.data??[]) as unknown as Post[]);},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(timer);},[load]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const s=createClient();const limit=await s.rpc("check_rate_limit",{p_operation:"create_post",p_limit:5,p_window_seconds:60});if(limit.data!==true)return setMessage("โพสต์ถี่เกินไป");const r=await s.from("posts").insert({author_id:userId,body:body.trim(),status:"published"});if(r.error)setMessage(r.error.message);else{setBody("");await load();}};
 const like=async(p:Post)=>{const s=createClient();const liked=p.post_reactions.some((x)=>x.user_id===userId);if(liked)await s.from("post_reactions").delete().eq("post_id",p.id).eq("user_id",userId);else await s.from("post_reactions").upsert({post_id:p.id,user_id:userId,reaction:"like"});await load();};
 const report=async(id:string)=>{const r=await createClient().from("reports").insert({reporter_id:userId,target_type:"post",target_id:id,reason:"misinformation"});setMessage(r.error?r.error.message:"ส่งรายงานแล้ว");};
 return <div className="space-y-4"><form onSubmit={submit} className="gold-card rounded-2xl p-4"><textarea required maxLength={2000} value={body} onChange={(e)=>setBody(e.target.value)} placeholder="แชร์ความฝันหรือชุดเลข..." className="w-full rounded-xl bg-[#10101b] p-3" /><button className="gold-button mt-3 w-full rounded-xl py-3 font-bold">โพสต์</button></form>{message?<p className="text-xs text-[#d6b867]">{message}</p>:null}{posts.length?posts.map((p)=><article key={p.id} className="glass-card rounded-2xl p-4"><div className="flex justify-between"><strong>สมาชิก Teehauy</strong><button type="button" onClick={()=>void report(p.id)} className="text-[10px] text-[#596071]">รายงาน</button></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{p.body}</p><button type="button" onClick={()=>void like(p)} className="mt-3 text-xs text-[#f0c040]">♥ {p.post_reactions.length}</button></article>):<div className="glass-card rounded-2xl p-6 text-center text-sm">ยังไม่มีโพสต์</div>}</div>;
}
