"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { createClient } from "@/lib/supabase/client";
type Draw = { id: string; draw_date: string };
type Ticket = { id: string; ticket_number: string; quantity: number; ticket_wins: { prize_amount: number }[] };
export function TicketsPage({ userId }: { userId: string }) {
  const [draws, setDraws] = useState<Draw[]>([]); const [tickets, setTickets] = useState<Ticket[]>([]); const [drawId, setDrawId] = useState(""); const [number, setNumber] = useState(""); const [quantity, setQuantity] = useState(1); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { const s = createClient(); const [a,b] = await Promise.all([s.from("lottery_draws").select("id, draw_date").in("status", ["scheduled","published","verified"]).order("draw_date", { ascending:false }), s.from("user_tickets").select("id,ticket_number,quantity,ticket_wins(prize_amount)").order("created_at",{ascending:false})]); const d=(a.data??[]) as Draw[]; setDraws(d); setDrawId((v)=>v||d[0]?.id||""); setTickets((b.data??[]) as unknown as Ticket[]); }, []);
  useEffect(() => { const timer=window.setTimeout(()=>{void load();},0); return()=>window.clearTimeout(timer); }, [load]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!/^\d{6}$/.test(number))return setMessage("เลขสลากต้องมี 6 หลัก");const result=await createClient().from("user_tickets").upsert({user_id:userId,draw_id:drawId,ticket_number:number,quantity},{onConflict:"user_id,draw_id,ticket_number"});if(result.error)setMessage(result.error.message);else{setNumber("");setMessage("บันทึกสลากแล้ว");await load();}};
  return <div className="space-y-5"><div className="rounded-2xl border border-[#80d0c033] p-4 text-xs text-[#91cfc2]">เก็บสลากที่ซื้อจริงแยกจากเลขทำนาย และตรวจเมื่อผลทางการยืนยันแล้ว</div><form onSubmit={submit} className="gold-card space-y-3 rounded-2xl p-4"><select value={drawId} onChange={(e)=>setDrawId(e.target.value)} className="w-full rounded-xl bg-[#13131f] p-3">{draws.map((d)=><option key={d.id} value={d.id}>งวด {d.draw_date}</option>)}</select><div className="grid grid-cols-[1fr_80px] gap-3"><input required inputMode="numeric" maxLength={6} value={number} onChange={(e)=>setNumber(e.target.value.replace(/\D/g,""))} placeholder="เลข 6 หลัก" className="rounded-xl bg-[#13131f] p-3" /><input aria-label="จำนวนใบ" type="number" min={1} max={100} value={quantity} onChange={(e)=>setQuantity(Number(e.target.value))} className="rounded-xl bg-[#13131f] p-3" /></div><button className="gold-button w-full rounded-xl py-3 font-bold">เพิ่มสลาก</button>{message?<p className="text-xs text-[#d6b867]">{message}</p>:null}</form>{tickets.map((t)=><article key={t.id} className="glass-card flex justify-between rounded-2xl p-4"><strong className="text-xl text-[#f0c040]">{t.ticket_number}</strong><span className="text-xs text-[#687183]">{t.ticket_wins.length?"พบรางวัล":"รอตรวจผล"} · {t.quantity} ใบ</span></article>)}</div>;
}
